set_power_mode:
  description: Set power mode for a device
  fields:
    rig_id:
      description: ID of the Rig
      example: "0-AAbbCCddEE112233445566"
      required: true
    device_id:
      description: ID of the Device
      example: "2-aaBBccDDee665544332211"
      required: true
    power_mode:
      description: Power Mode
      example: "HIGH"
      required: true
